// WARNING: AUTOGENERATED, DO NOT OVERWRITE

#ifndef ARG_H
#define ARG_H

struct Arg {
  char val[52];
  struct Arg* nxt;
};
typedef struct Arg Arg;

Arg* appendNewArg(Arg* arg);
void freeArg(Arg* arg);
Arg* newArg();
char* catArg(char* m, Arg* arg);

#endif // ARG_h
