// WARNING: AUTOGENERATED, DO NOT OVERWRITE

#ifndef Tes_H
#define Tes_H

struct Tes {
  char* val;
  struct Tes* nxt;
};
typedef struct Tes Tes;

Tes* newTes();
void freeTes(Tes* arg);
char* catTes(char* m, Tes* arg);
#endif // Tes_h